import Head from 'next/head'
import Image from 'next/image'
import Body from '../componets/Body'
import Descr from '../componets/descr'
import Service from '../componets/service'
import Work from '../componets/nextwork'
import Myfolio from '../componets/Myfolio'
import Button from '../componets/button'
import Copyright from '../componets/copyright'
import Navbar from '../componets/navbar'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar/>
        <Body/>
        <Descr/>
        <Service/>
        <Work/>
        <Myfolio/>
        <Button/>
        <Copyright/>
        
        
      </main>

      <footer className={styles.footer}>
         
      </footer>
    </div>
  )
}
